

about :

  name : wUriFundamentals
  description : Collection of routines to operate URI(s) in the reliable and consistent way. UriFundamentals leverages parsing, joining, extracting, normalizing, nativizing, resolving URI(s). Use the module to get uniform experience from playing with URI(s) on different platforms.
  version : 0.6.52
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wUriFundamentals.git
  bugs : https://github.com/Wandalen/wUriFundamentals/issues

build :

  debug.raw.export :
    exportDirPath : path::out.debug
    criterion :
      default : 1
      debug : 1
      raw : 1
      export : 1
      tar : 0
    steps :
      # - build::.debug.raw
      - step::export

  release.compiled.export :
    exportDirPath : path::out.release
    criterion :
      debug : 0
      raw : 0
      export : 1
      tar : 0
    steps :
      - build::release.compiled
      - step::export

  export.all :
    steps :
      - build::debug.raw.export
      - build::release.compiled.export

